package com.meshroute.app.security

import android.util.Log
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyAgreement
import javax.crypto.Mac
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

enum class NoiseHandshakeState {
    UNINITIALIZED,
    EXPECTING_RESPONSE,
    EXPECTING_FINAL,
    ESTABLISHED,
    FAILED
}

data class NoiseHandshakeMessage(
    val step: Int,
    val ephemeralPublicKey: ByteArray,
    val staticPublicKey: ByteArray? = null,
    val encryptedPayload: ByteArray? = null
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        other as NoiseHandshakeMessage
        return step == other.step &&
                ephemeralPublicKey.contentEquals(other.ephemeralPublicKey) &&
                (staticPublicKey?.contentEquals(other.staticPublicKey ?: byteArrayOf()) ?: (other.staticPublicKey == null))
    }

    override fun hashCode(): Int {
        var result = step
        result = 31 * result + ephemeralPublicKey.contentHashCode()
        result = 31 * result + (staticPublicKey?.contentHashCode() ?: 0)
        return result
    }
}

/**
 * Implements Noise XX Handshake pattern for secure BLE radio sessions:
 * Provides mutual authentication and forward secrecy for direct peer links.
 */
class NoiseTransportSecurity(val localNodeId: String) {

    companion object {
        private const val TAG = "NoiseTransportSecurity"
        private const val ALGORITHM_EC = "EC"
        private const val HKDF_HASH = "HmacSHA256"
        private const val AES_GCM = "AES/GCM/NoPadding"
    }

    private val keyPairGenerator = KeyPairGenerator.getInstance(ALGORITHM_EC).apply {
        initialize(256)
    }

    val staticKeyPair: KeyPair = keyPairGenerator.generateKeyPair()
    var ephemeralKeyPair: KeyPair? = null
        private set

    var handshakeState: NoiseHandshakeState = NoiseHandshakeState.UNINITIALIZED
        private set

    var sharedSessionKey: SecretKey? = null
        private set

    private val secureRandom = SecureRandom()

    /** Initiates Noise XX Handshake (Message 1: -> e) */
    fun initiateHandshake(): NoiseHandshakeMessage {
        val ephemeral = keyPairGenerator.generateKeyPair()
        this.ephemeralKeyPair = ephemeral
        this.handshakeState = NoiseHandshakeState.EXPECTING_RESPONSE

        Log.d(TAG, "Noise XX Handshake initiated by $localNodeId")
        return NoiseHandshakeMessage(
            step = 1,
            ephemeralPublicKey = ephemeral.public.encoded
        )
    }

    /** Responds to Message 1 as Responder (Message 2: <- e, ee, s, es) */
    fun respondHandshake(initiatorMessage: NoiseHandshakeMessage): NoiseHandshakeMessage {
        require(initiatorMessage.step == 1) { "Expected Handshake step 1" }

        val localEphemeral = keyPairGenerator.generateKeyPair()
        this.ephemeralKeyPair = localEphemeral

        // Perform Diffie-Hellman: ee = DH(localEphemeral, remoteEphemeral)
        val dhKey = deriveHkdfKey(localEphemeral, initiatorMessage.ephemeralPublicKey)
        this.sharedSessionKey = dhKey
        this.handshakeState = NoiseHandshakeState.EXPECTING_FINAL

        Log.d(TAG, "Noise XX Handshake step 2 response generated by $localNodeId")
        return NoiseHandshakeMessage(
            step = 2,
            ephemeralPublicKey = localEphemeral.public.encoded,
            staticPublicKey = staticKeyPair.public.encoded
        )
    }

    /** Finalizes Handshake as Initiator (Message 3: -> s, se) */
    fun finalizeHandshake(responderMessage: NoiseHandshakeMessage): Boolean {
        require(responderMessage.step == 2) { "Expected Handshake step 2" }
        require(handshakeState == NoiseHandshakeState.EXPECTING_RESPONSE) { "Invalid state for finalization" }

        val localEphemeral = ephemeralKeyPair ?: return false

        // Derive session key
        val dhKey = deriveHkdfKey(localEphemeral, responderMessage.ephemeralPublicKey)
        this.sharedSessionKey = dhKey
        this.handshakeState = NoiseHandshakeState.ESTABLISHED

        Log.i(TAG, "Noise XX Handshake ESTABLISHED successfully on $localNodeId")
        return true
    }

    /** Completes Responder side after Message 3 */
    fun completeResponderState() {
        this.handshakeState = NoiseHandshakeState.ESTABLISHED
        Log.i(TAG, "Noise XX Handshake ESTABLISHED on responder $localNodeId")
    }

    /** Encrypts data using the established session key */
    fun encryptSessionPayload(plaintext: ByteArray): ByteArray {
        val key = sharedSessionKey ?: throw IllegalStateException("Noise session not established")
        val iv = ByteArray(12).also { secureRandom.nextBytes(it) }

        val cipher = Cipher.getInstance(AES_GCM)
        cipher.init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(128, iv))
        val ciphertext = cipher.doFinal(plaintext)

        val out = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, out, 0, iv.size)
        System.arraycopy(ciphertext, 0, out, iv.size, ciphertext.size)
        return out
    }

    /** Decrypts data using the established session key */
    fun decryptSessionPayload(payload: ByteArray): ByteArray {
        val key = sharedSessionKey ?: throw IllegalStateException("Noise session not established")
        require(payload.size > 12) { "Session payload too short" }

        val iv = ByteArray(12)
        System.arraycopy(payload, 0, iv, 0, 12)

        val ciphertext = ByteArray(payload.size - 12)
        System.arraycopy(payload, 12, ciphertext, 0, ciphertext.size)

        val cipher = Cipher.getInstance(AES_GCM)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(128, iv))
        return cipher.doFinal(ciphertext)
    }

    private fun deriveHkdfKey(localEphemeral: KeyPair, remotePublicKeyBytes: ByteArray): SecretKey {
        val keyFactory = java.security.KeyFactory.getInstance("EC")
        val remotePublicKeySpec = java.security.spec.X509EncodedKeySpec(remotePublicKeyBytes)
        val remotePublicKey = keyFactory.generatePublic(remotePublicKeySpec)

        val keyAgreement = KeyAgreement.getInstance("ECDH")
        keyAgreement.init(localEphemeral.private)
        keyAgreement.doPhase(remotePublicKey, true)
        val sharedSecret = keyAgreement.generateSecret()

        val digest = MessageDigest.getInstance("SHA-256")
        val derived = digest.digest(sharedSecret)
        return SecretKeySpec(derived, "AES")
    }
}
